import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
const app = await readFile(new URL("../src/app/pickingApp.mjs", import.meta.url), "utf8");
const css = await readFile(new URL("../src/styles/picking.css", import.meta.url), "utf8");
const labelOption = await readFile(new URL("../src/domain/labelOption.mjs", import.meta.url), "utf8");
assert.match(app, /import\s*\{\s*normalizeLabelOptionName\s*\}\s*from\s*"\.\.\/domain\/labelOption\.mjs/, "the label export must use the shared option normalizer");
assert.doesNotMatch(app, /function normalizeLabelOptionName\(/, "the app must not keep a second implementation that can drift from slips");
assert.match(labelOption, /export function normalizeLabelOptionName\(/);

for (const tab of ["dashboard", "picking", "shortage", "inspection", "cs", "custom-orders", "completed"]) {
  assert.match(html, new RegExp(`data-app-tab=["']${tab}["']`), `tab must remain wired: ${tab}`);
}
assert.match(html, /id="custom-orders-panel"/);
assert.match(html, /id="custom-orders-status"/);
assert.match(html, /id="custom-orders-supplier"/);
assert.match(html, /id="custom-orders-sort"/);
const workflowSort = html.match(/<select id="custom-orders-sort">([\s\S]*?)<\/select>/)?.[1];
assert.ok(workflowSort, "custom-order workflow must expose a sort selector");
for (const order of ["supplier_asc", "supplier_desc", "required_desc"]) {
  assert.match(workflowSort, new RegExp(`value="${order}"`), `workflow sort must support ${order}`);
}
assert.match(html, /id="custom-orders-date-criterion"/);
assert.match(html, /id="custom-orders-date-from"/);
assert.match(html, /id="custom-orders-date-to"/);
assert.match(html, /id="custom-orders-search"/);
assert.match(html, /data-custom-orders-view="workflow"/);
assert.match(html, /data-custom-orders-view="inbound"/);
assert.match(html, /id="custom-orders-inbound-source"/);
assert.match(html, /id="custom-orders-inbound-supplier"/);
assert.match(html, /id="custom-orders-inbound-date-from"/);
assert.match(html, /id="custom-orders-inbound-date-to"/);
assert.match(html, /id="custom-orders-inbound-sort"/);
assert.match(html, /id="custom-orders-inbound-search"/);
assert.match(html, /id="custom-orders-sku-schedule-panel"/);
assert.match(html, /id="custom-orders-sku-input"/);
assert.match(html, /id="custom-orders-sku-input"[^>]*placeholder="예: 1000-1"/);
assert.match(html, /id="custom-orders-sku-date"/);
assert.match(html, /id="custom-orders-sku-own-code"/);
assert.match(html, /id="custom-orders-sku-own-code"[^>]*placeholder="예: GPA-14-19_5"/);
assert.match(html, /id="custom-orders-sku-upload"/);
assert.match(html, /id="custom-orders-sku-download"/);
assert.match(html, /셀피아 SKU \| 입고예정일 \| 자사코드/);

const tabStart = app.indexOf("function setActiveTab");
const tabEnd = app.indexOf("function scrollToTrayItem", tabStart);
const tabSource = app.slice(tabStart, tabEnd);
assert.match(tabSource, /state\.activeTab === "custom-orders"/);
assert.match(tabSource, /!state\.customOrders\.loaded/);
assert.match(tabSource, /loadCustomOrdersData\(\)/, "custom orders must lazy-load on first tab entry");

assert.match(app, /data-action="custom-order-toggle"/);
assert.match(app, /data-action="custom-order-memo-save"/);
assert.match(app, /class="custom-order-memo-inline"/);
assert.doesNotMatch(app, /<details class="custom-order-memo"/);
assert.match(app, /canClearCustomRequired\(existing\)/);
assert.match(app, /주문제작 탭에서 취소 처리/);
assert.match(app, /internal_memo: memo \|\| null/);
assert.match(app, /data-custom-order-action="ordered-today"/);
assert.match(app, /addCalendarDays\(orderedOn, 14\)/);
assert.match(app, /class="custom-order-product-photo"/);
const customOrderRenderer = app.slice(app.indexOf("function renderCustomOrderRow"), app.indexOf("function inboundRowIdentity"));
assert.match(customOrderRenderer, /custom-order-row custom-order-slip-card/);
assert.match(customOrderRenderer, /class="custom-order-slip-facts"/);
assert.match(customOrderRenderer, /class="custom-order-slip-quantity(?:\s|")/);
assert.match(customOrderRenderer, /class="custom-order-slip-management"/);
assert.match(customOrderRenderer, /class="custom-order-slip-management-heading"/);
const primarySlipSource = customOrderRenderer.slice(
  customOrderRenderer.indexOf('<div class="custom-order-row-primary '),
  customOrderRenderer.indexOf('<div class="custom-order-slip-management">'),
);
assert.match(primarySlipSource, /custom-order-product-photo/);
assert.match(primarySlipSource, /custom-order-supplier/);
assert.match(primarySlipSource, /custom-order-slip-facts/);
assert.match(primarySlipSource, /custom-order-slip-quantity/);
assert.doesNotMatch(primarySlipSource, /custom-order-status|workflow-row-badge|custom-order-slip-source|data-custom-order-field|data-custom-order-action/, "the left capture area must contain only supplier order-slip content");
assert.match(customOrderRenderer, /옵션/);
assert.match(customOrderRenderer, /바길이/);
assert.match(customOrderRenderer, /업체상품코드/);
assert.match(customOrderRenderer, /미수집/, "supplier product codes must not be invented from a different code");
assert.match(customOrderRenderer, /const supplierCode = customOrderSupplierCode\(display\.arbitraryFieldRaw\)/, "supplier display must shorten only the dedicated raw field with the domain helper");
assert.match(primarySlipSource, /<dt>옵션<\/dt>[\s\S]*?<dt>바길이<\/dt>[\s\S]*?<dt>업체상품코드<\/dt>[\s\S]*?<dt>수량<\/dt>/, "capture facts must follow the requested horizontal reading order");
const vendorCodeSource = primarySlipSource.match(/<div><dt>업체상품코드<\/dt>([\s\S]*?)<\/dd><\/div>/)?.[1];
assert.ok(vendorCodeSource, "the capture area must expose a vendor-code field");
assert.match(vendorCodeSource, /display\.arbitraryFieldRaw/, "vendor codes must use the dedicated raw Sellpia arbitrary field");
assert.match(vendorCodeSource, /escapeHtml\(supplierCode \|\| "미수집"\)/, "shortened vendor-code text must be escaped before rendering");
assert.match(vendorCodeSource, /is-unavailable/, "missing vendor codes must retain their unavailable styling");
assert.match(vendorCodeSource, /title="\$\{escapeHtml\(display\.arbitraryFieldRaw \|\| ""\)\}/, "the complete raw vendor-code text must remain available in an escaped title");
assert.match(primarySlipSource, /<dd title="\$\{escapeHtml\(display\.productOption \|\| ""\)\}/, "normalized options must retain the full escaped option in a title");
assert.match(customOrderRenderer, /원본 업체상품코드 \$\{escapeHtml\(display\.arbitraryFieldRaw\)\}/, "shortened vendor codes must retain their raw text in source details");
assert.doesNotMatch(vendorCodeSource, /display\.(?:ownCode|sellpiaProductCode)/, "own codes and Sellpia SKUs must never be substituted for missing vendor codes");
assert.match(customOrderRenderer, /slip\.quantity === null \? "확인 필요"/, "missing source quantities must remain visibly unknown");
assert.match(app, /customOrderSlipDetails/);
assert.match(app, /sortCustomOrderRows/);
assert.match(app, /sort: "supplier_asc"/, "workflow sort must initially group suppliers in ascending order");
assert.match(app, /<section class="custom-order-supplier-group"/, "supplier-sorted workflow rows must be wrapped in supplier sections");
assert.match(app, /<h3[^>]*class="custom-order-supplier-group-head"/, "supplier sections must contain a semantic compact header");
assert.match(app, /class="custom-order-supplier-group-items"/, "supplier cards must follow their group heading in a dedicated container");
assert.match(app, /data-custom-order-supplier="\$\{escapeHtml\(/, "raw supplier text must be escaped in group identity attributes");
assert.match(app, /엑셀 열:[\s\S]*셀피아 SKU \| 입고예정일\(YYYY-MM-DD\) \| 자사코드\(선택\)/);
assert.match(app, /1000-1 \| 2026-10-08 \| GPA-14-19_5/);
assert.match(app, /data-custom-order-action="received-today"/);
assert.match(app, /data-custom-order-action="cancel"/);
assert.match(app, /custom_cancelled_at: new Date\(\)\.toISOString\(\)/);
assert.match(app, /inbound_expected_source: "manual"/);
assert.match(app, /loadCustomOrderWorkspace/);
assert.match(app, /buildInboundExpectedRows/);
assert.match(app, /sortInboundExpectedRows/);
assert.match(app, /data-inbound-expected-field="inbound_expected_date"/);
assert.match(app, /upsertOperationForCurrentOrderItem\(currentItem/);
assert.match(app, /skuInboundSchedules\.upsertSchedule/);
assert.match(app, /skuInboundSchedules\.upsertSchedules/);
assert.match(app, /parseSkuInboundScheduleRows/);
assert.match(app, /SKU_INBOUND_SCHEDULE_HEADERS/);
assert.doesNotMatch(app, /from\("order_item_operations"\)\.delete/, "UI must never delete operation rows");
assert.match(css, /\.custom-orders-toolbar/);
assert.match(css, /\.custom-order-row/);
assert.match(css, /\.custom-order-slip-card/);
assert.match(css, /\.custom-order-slip-facts/);
const slipFactsCss = css.match(/\.custom-order-slip-facts\s*\{([^}]*)\}/)?.[1];
assert.match(slipFactsCss, /grid-template-columns:\s*(?:minmax\([^)]*\)\s*){4};/, "the four production facts must form a horizontal strip");
const slipFactValueCss = css.match(/\.custom-order-slip-facts dd\s*\{([^}]*)\}/)?.[1];
assert.match(slipFactValueCss, /font-size:\s*1\.75rem\s*;/, "the production facts must be enlarged for capture and reading");
assert.match(css, /\.custom-order-slip-management/);
assert.match(css, /\.custom-order-supplier-group\s*\{/, "supplier sections must have scoped layout rules");
assert.match(css, /\.custom-order-supplier-group-head\s*\{/, "compact supplier headers must be styled independently of workflow cards");
assert.match(css, /\.custom-order-supplier-group-items\s*\{/, "grouped cards must retain a dedicated layout container");
assert.match(css, /(?:#custom-orders-list|\.custom-orders-list)\s*\{[^}]*grid-row:\s*6\s*;/, "workflow list must occupy the final panel grid row");
const slipPhotoCss = css.match(/\.custom-order-slip-card \.custom-order-product-photo\s*\{([^}]*)\}/)?.[1];
assert.ok(slipPhotoCss, "workflow photos must have scoped size rules");
assert.match(slipPhotoCss, /display:\s*block\s*;/, "workflow frames must avoid shared grid intrinsic image-height expansion");
assert.match(slipPhotoCss, /width:\s*15rem\s*;/);
assert.match(slipPhotoCss, /min-width:\s*15rem\s*;/);
assert.match(slipPhotoCss, /height:\s*11\.25rem\s*;/, "workflow photos must have the requested fixed 4:3 frame height");
assert.match(slipPhotoCss, /aspect-ratio:\s*4\s*\/\s*3\s*;/, "workflow photos must override the shared square ratio with 4:3");
const slipPhotoImageCss = css.match(/\.custom-order-slip-card \.custom-order-product-photo img\s*\{([^}]*)\}/)?.[1];
assert.ok(slipPhotoImageCss, "workflow photo image sizing must be scoped to order slips");
assert.match(slipPhotoImageCss, /display:\s*block\s*;/);
assert.match(slipPhotoImageCss, /width:\s*100%\s*;/);
assert.match(slipPhotoImageCss, /height:\s*100%\s*;/, "workflow image elements must fit the fixed frame height");
assert.match(slipPhotoImageCss, /object-fit:\s*contain\s*;/);
assert.match(css, /\.custom-orders-subtabs/);
assert.match(css, /\.inbound-expected-row/);
assert.match(css, /\.picking-custom-order/);
assert.match(css, /\.custom-order-row\.status-before_order/);
assert.match(css, /\.custom-order-row\.status-ordered/);
assert.match(css, /\.custom-order-row\.status-received/);
assert.match(css, /\.sku-inbound-schedule-panel/);

console.log("customOrderUi.contract.test: OK");
