-- Persistent combined-shipment grouping.
--
-- Original Sellpia order and item identities remain in orders/order_items.
-- These tables only describe the System V3 grouping so scraper replacement of
-- order_items cannot erase or rewrite a combined-shipment decision.

create table if not exists public.shipment_groups (
  id uuid primary key default gen_random_uuid(),
  representative_ord_no text not null,
  target_inv_no text not null,
  status text not null default 'active',
  sync_status text not null default 'pending',
  version integer not null default 1,
  created_by text null,
  released_by text null,
  released_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shipment_groups_status_check check (status in ('active', 'released')),
  constraint shipment_groups_sync_status_check check (sync_status in ('pending', 'synced', 'failed')),
  constraint shipment_groups_version_check check (version > 0),
  constraint shipment_groups_representative_ord_no_check check (length(btrim(representative_ord_no)) > 0),
  constraint shipment_groups_target_inv_no_check check (length(btrim(target_inv_no)) > 0)
);

create table if not exists public.shipment_group_members (
  group_id uuid not null references public.shipment_groups(id) on delete restrict,
  ord_no text not null,
  original_inv_no text null,
  member_order integer not null,
  active boolean not null default true,
  joined_at timestamptz not null default now(),
  released_at timestamptz null,
  primary key (group_id, ord_no),
  constraint shipment_group_members_ord_no_check check (length(btrim(ord_no)) > 0),
  constraint shipment_group_members_member_order_check check (member_order > 0)
);

create table if not exists public.shipment_group_events (
  id bigint generated by default as identity primary key,
  group_id uuid not null references public.shipment_groups(id) on delete restrict,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_by text null,
  created_at timestamptz not null default now(),
  constraint shipment_group_events_type_check check (
    event_type in ('created', 'representative_changed', 'released', 'sync_status_changed', 'drawer_memo_updated')
  )
);

create unique index if not exists shipment_group_members_one_active_group_idx
  on public.shipment_group_members (ord_no)
  where active;
create unique index if not exists shipment_group_members_order_idx
  on public.shipment_group_members (group_id, member_order);
create index if not exists shipment_groups_status_updated_at_idx
  on public.shipment_groups (status, updated_at desc);
create index if not exists shipment_group_events_group_created_at_idx
  on public.shipment_group_events (group_id, created_at desc);

create or replace function public.set_shipment_groups_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists shipment_groups_set_updated_at on public.shipment_groups;
create trigger shipment_groups_set_updated_at
before update on public.shipment_groups
for each row execute function public.set_shipment_groups_updated_at();

alter table public.shipment_groups enable row level security;
alter table public.shipment_group_members enable row level security;
alter table public.shipment_group_events enable row level security;

-- System V3 currently operates without a Supabase Auth session. These grants
-- deliberately mirror the existing workflow/CS operational model. The RPCs
-- below remain SECURITY INVOKER and enforce the cross-row invariants. Replace
-- these anon policies with operator ownership policies when Auth is introduced.
revoke all on table public.shipment_groups from anon, authenticated;
revoke all on table public.shipment_group_members from anon, authenticated;
revoke all on table public.shipment_group_events from anon, authenticated;

grant select, insert, update on table public.shipment_groups to anon, authenticated;
grant select, insert, update on table public.shipment_group_members to anon, authenticated;
grant select, insert on table public.shipment_group_events to anon, authenticated;
grant usage, select on sequence public.shipment_group_events_id_seq to anon, authenticated;

drop policy if exists "shipment groups read" on public.shipment_groups;
drop policy if exists "shipment groups create" on public.shipment_groups;
drop policy if exists "shipment groups update" on public.shipment_groups;
create policy "shipment groups read" on public.shipment_groups
  for select to anon, authenticated using (true);
create policy "shipment groups create" on public.shipment_groups
  for insert to anon, authenticated
  with check (
    status = 'active'
    and sync_status in ('pending', 'synced')
    and version = 1
    and length(btrim(representative_ord_no)) > 0
    and length(btrim(target_inv_no)) > 0
  );
create policy "shipment groups update" on public.shipment_groups
  for update to anon, authenticated
  using (true)
  with check (
    status in ('active', 'released')
    and sync_status in ('pending', 'synced', 'failed')
    and version > 0
  );

drop policy if exists "shipment group members read" on public.shipment_group_members;
drop policy if exists "shipment group members create" on public.shipment_group_members;
drop policy if exists "shipment group members update" on public.shipment_group_members;
create policy "shipment group members read" on public.shipment_group_members
  for select to anon, authenticated using (true);
create policy "shipment group members create" on public.shipment_group_members
  for insert to anon, authenticated
  with check (active and member_order > 0 and length(btrim(ord_no)) > 0);
create policy "shipment group members update" on public.shipment_group_members
  for update to anon, authenticated
  using (true)
  with check (member_order > 0 and length(btrim(ord_no)) > 0);

drop policy if exists "shipment group events read" on public.shipment_group_events;
drop policy if exists "shipment group events create" on public.shipment_group_events;
create policy "shipment group events read" on public.shipment_group_events
  for select to anon, authenticated using (true);
create policy "shipment group events create" on public.shipment_group_events
  for insert to anon, authenticated
  with check (
    event_type in ('created', 'representative_changed', 'released', 'sync_status_changed', 'drawer_memo_updated')
  );

create or replace function public.shipment_group_snapshot(p_group_id uuid)
returns jsonb
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'group', to_jsonb(g),
    'members', coalesce(
      jsonb_agg(to_jsonb(m) order by m.member_order) filter (where m.group_id is not null),
      '[]'::jsonb
    )
  )
  from public.shipment_groups g
  left join public.shipment_group_members m on m.group_id = g.id
  where g.id = p_group_id
  group by g.id;
$$;

create or replace function public.create_shipment_group(
  p_ord_nos text[],
  p_representative_ord_no text,
  p_created_by text default 'system-v3-front'
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_ord_nos text[];
  v_representative_ord_no text := btrim(coalesce(p_representative_ord_no, ''));
  v_target_inv_no text;
  v_group_id uuid;
  v_sync_status text;
  v_distinct_count integer;
begin
  select array_agg(ord_no order by first_position)
    into v_ord_nos
  from (
    select btrim(value) as ord_no, min(ordinality) as first_position
    from unnest(coalesce(p_ord_nos, array[]::text[])) with ordinality as input(value, ordinality)
    where length(btrim(value)) > 0
    group by btrim(value)
  ) normalized;

  if coalesce(cardinality(v_ord_nos), 0) < 2 then
    raise exception 'shipment_group_requires_at_least_two_orders';
  end if;
  if not (v_representative_ord_no = any(v_ord_nos)) then
    raise exception 'representative_order_must_be_a_member';
  end if;

  perform 1
  from public.orders
  where ord_no = any(v_ord_nos)
  for update;

  if (select count(*) from public.orders where ord_no = any(v_ord_nos)) <> cardinality(v_ord_nos) then
    raise exception 'shipment_group_order_not_found';
  end if;
  if exists (
    select 1
    from public.shipment_group_members
    where active and ord_no = any(v_ord_nos)
  ) then
    raise exception 'shipment_group_order_already_active';
  end if;

  select count(distinct nullif(lower(regexp_replace(coalesce(receiver_name, receiver, ''), '[[:space:]]+', '', 'g')), ''))
    into v_distinct_count
  from public.orders
  where ord_no = any(v_ord_nos);
  if v_distinct_count > 1 then
    raise exception 'shipment_group_receiver_mismatch';
  end if;

  select count(distinct nullif(regexp_replace(coalesce(receiver_mobile, receiver_tel, ''), '[^0-9]+', '', 'g'), ''))
    into v_distinct_count
  from public.orders
  where ord_no = any(v_ord_nos);
  if v_distinct_count > 1 then
    raise exception 'shipment_group_phone_mismatch';
  end if;

  select count(distinct nullif(lower(regexp_replace(coalesce(receiver_address, ''), '[[:space:]]+', '', 'g')), ''))
    into v_distinct_count
  from public.orders
  where ord_no = any(v_ord_nos);
  if v_distinct_count > 1 then
    raise exception 'shipment_group_address_mismatch';
  end if;

  select nullif(btrim(inv_no), '')
    into v_target_inv_no
  from public.orders
  where ord_no = v_representative_ord_no;
  if v_target_inv_no is null then
    raise exception 'representative_order_invoice_required';
  end if;

  select case
    when bool_and(coalesce(nullif(btrim(inv_no), '') = v_target_inv_no, false)) then 'synced'
    else 'pending'
  end
    into v_sync_status
  from public.orders
  where ord_no = any(v_ord_nos);

  insert into public.shipment_groups (
    representative_ord_no,
    target_inv_no,
    status,
    sync_status,
    version,
    created_by
  ) values (
    v_representative_ord_no,
    v_target_inv_no,
    'active',
    v_sync_status,
    1,
    nullif(btrim(coalesce(p_created_by, '')), '')
  )
  returning id into v_group_id;

  insert into public.shipment_group_members (
    group_id,
    ord_no,
    original_inv_no,
    member_order,
    active
  )
  select
    v_group_id,
    input.ord_no,
    nullif(btrim(o.inv_no), ''),
    input.ordinality::integer,
    true
  from unnest(v_ord_nos) with ordinality as input(ord_no, ordinality)
  join public.orders o on o.ord_no = input.ord_no;

  insert into public.shipment_group_events (group_id, event_type, payload, created_by)
  values (
    v_group_id,
    'created',
    jsonb_build_object(
      'ord_nos', to_jsonb(v_ord_nos),
      'representative_ord_no', v_representative_ord_no,
      'target_inv_no', v_target_inv_no,
      'sync_status', v_sync_status
    ),
    nullif(btrim(coalesce(p_created_by, '')), '')
  );

  return public.shipment_group_snapshot(v_group_id);
end;
$$;

create or replace function public.change_shipment_representative(
  p_group_id uuid,
  p_representative_ord_no text,
  p_expected_version integer,
  p_updated_by text default 'system-v3-front'
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_group public.shipment_groups%rowtype;
  v_representative_ord_no text := btrim(coalesce(p_representative_ord_no, ''));
  v_target_inv_no text;
  v_sync_status text;
begin
  select * into v_group
  from public.shipment_groups
  where id = p_group_id
  for update;

  if not found then raise exception 'shipment_group_not_found'; end if;
  if v_group.status <> 'active' then raise exception 'shipment_group_not_active'; end if;
  if v_group.version <> p_expected_version then raise exception 'shipment_group_version_conflict'; end if;
  if not exists (
    select 1 from public.shipment_group_members
    where group_id = p_group_id and ord_no = v_representative_ord_no and active
  ) then
    raise exception 'representative_order_must_be_an_active_member';
  end if;

  select nullif(btrim(inv_no), '') into v_target_inv_no
  from public.orders
  where ord_no = v_representative_ord_no;
  if v_target_inv_no is null then raise exception 'representative_order_invoice_required'; end if;

  select case
    when bool_and(coalesce(nullif(btrim(o.inv_no), '') = v_target_inv_no, false)) then 'synced'
    else 'pending'
  end into v_sync_status
  from public.shipment_group_members m
  join public.orders o on o.ord_no = m.ord_no
  where m.group_id = p_group_id and m.active;

  update public.shipment_groups
  set representative_ord_no = v_representative_ord_no,
      target_inv_no = v_target_inv_no,
      sync_status = v_sync_status,
      version = version + 1
  where id = p_group_id;

  insert into public.shipment_group_events (group_id, event_type, payload, created_by)
  values (
    p_group_id,
    'representative_changed',
    jsonb_build_object(
      'previous_representative_ord_no', v_group.representative_ord_no,
      'representative_ord_no', v_representative_ord_no,
      'target_inv_no', v_target_inv_no,
      'sync_status', v_sync_status
    ),
    nullif(btrim(coalesce(p_updated_by, '')), '')
  );

  return public.shipment_group_snapshot(p_group_id);
end;
$$;

create or replace function public.release_shipment_group(
  p_group_id uuid,
  p_expected_version integer,
  p_released_by text default 'system-v3-front'
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_group public.shipment_groups%rowtype;
begin
  select * into v_group
  from public.shipment_groups
  where id = p_group_id
  for update;

  if not found then raise exception 'shipment_group_not_found'; end if;
  if v_group.status <> 'active' then raise exception 'shipment_group_not_active'; end if;
  if v_group.version <> p_expected_version then raise exception 'shipment_group_version_conflict'; end if;

  update public.shipment_group_members
  set active = false,
      released_at = now()
  where group_id = p_group_id and active;

  update public.shipment_groups
  set status = 'released',
      released_by = nullif(btrim(coalesce(p_released_by, '')), ''),
      released_at = now(),
      version = version + 1
  where id = p_group_id;

  insert into public.shipment_group_events (group_id, event_type, payload, created_by)
  values (
    p_group_id,
    'released',
    jsonb_build_object(
      'representative_ord_no', v_group.representative_ord_no,
      'target_inv_no', v_group.target_inv_no
    ),
    nullif(btrim(coalesce(p_released_by, '')), '')
  );

  return public.shipment_group_snapshot(p_group_id);
end;
$$;

create or replace function public.save_shipment_group_drawer_memo(
  p_group_id uuid,
  p_drawer_memo text,
  p_expected_version integer,
  p_auto_hold boolean,
  p_updated_by text
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_group public.shipment_groups%rowtype;
  v_drawer_memo text := coalesce(p_drawer_memo, '');
  v_held_ord_nos text[] := array[]::text[];
begin
  select * into v_group
  from public.shipment_groups
  where id = p_group_id
  for update;

  if not found then raise exception 'shipment_group_not_found'; end if;
  if v_group.status <> 'active' then raise exception 'shipment_group_not_active'; end if;
  if v_group.version <> p_expected_version then raise exception 'shipment_group_version_conflict'; end if;

  update public.order_items oi
  set o_shop_memo = v_drawer_memo
  where exists (
    select 1
    from public.shipment_group_members m
    where m.group_id = p_group_id
      and m.active
      and m.ord_no = oi.ord_no
  );

  update public.picking p
  set drawer_no = v_drawer_memo
  where exists (
    select 1
    from public.shipment_group_members m
    where m.group_id = p_group_id
      and m.active
      and m.ord_no = p.ord_no
  );

  if coalesce(p_auto_hold, false) and length(btrim(v_drawer_memo)) > 0 then
    with changed_orders as (
      update public.orders o
      set system_shipping_hold_status = 'ON',
          system_shipping_hold_source = 'shipment_memo_auto_hold',
          system_shipping_hold_updated_at = now()
      where o.system_shipping_hold_status is distinct from 'ON'
        and exists (
          select 1
          from public.shipment_group_members m
          where m.group_id = p_group_id
            and m.active
            and m.ord_no = o.ord_no
        )
      returning o.*
    ), inserted_events as (
      insert into public.workflow_invoice_events (
        receipt_date,
        order_group_no,
        invoice_no,
        event_type,
        memo,
        actor,
        source,
        payload
      )
      select
        changed.receipt_date,
        changed.ord_no,
        coalesce(changed.inv_no, ''),
        'hold_created',
        'shipping hold auto on by shipment drawer memo save',
        nullif(btrim(coalesce(p_updated_by, '')), ''),
        'f_v1_shipment_group',
        jsonb_build_object('group_id', p_group_id, 'reason', 'drawer_memo')
      from changed_orders changed
      returning order_group_no
    )
    select coalesce(array_agg(order_group_no order by order_group_no), array[]::text[])
      into v_held_ord_nos
    from inserted_events;
  end if;

  insert into public.shipment_group_events (group_id, event_type, payload, created_by)
  values (
    p_group_id,
    'drawer_memo_updated',
    jsonb_build_object(
      'drawer_memo', v_drawer_memo,
      'held_ord_nos', to_jsonb(v_held_ord_nos)
    ),
    nullif(btrim(coalesce(p_updated_by, '')), '')
  );

  return jsonb_build_object(
    'snapshot', public.shipment_group_snapshot(p_group_id),
    'drawer_memo', v_drawer_memo,
    'held_ord_nos', to_jsonb(v_held_ord_nos)
  );
end;
$$;

create or replace function public.save_shipment_group_item_memo2(
  p_group_id uuid,
  p_ord_no text,
  p_item_no text,
  p_memo2 text,
  p_event_type text,
  p_quantity numeric,
  p_drawer_memo text,
  p_expected_version integer,
  p_auto_hold boolean,
  p_updated_by text
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_group public.shipment_groups%rowtype;
  v_ord_no text := btrim(coalesce(p_ord_no, ''));
  v_item_no text := btrim(coalesce(p_item_no, ''));
  v_memo2 text := coalesce(p_memo2, '');
  v_item public.order_items%rowtype;
  v_event public.workflow_item_events%rowtype;
  v_held_ord_nos text[] := array[]::text[];
begin
  select * into v_group
  from public.shipment_groups
  where id = p_group_id
  for update;

  if not found then raise exception 'shipment_group_not_found'; end if;
  if v_group.status <> 'active' then raise exception 'shipment_group_not_active'; end if;
  if v_group.version <> p_expected_version then raise exception 'shipment_group_version_conflict'; end if;
  if not exists (
    select 1
    from public.shipment_group_members
    where group_id = p_group_id and active and ord_no = v_ord_no
  ) then
    raise exception 'shipment_group_item_order_not_member';
  end if;
  if nullif(btrim(coalesce(p_event_type, '')), '') is not null
     and p_event_type not in ('shortage_created', 'shortage_qty_changed', 'shortage_repick_completed') then
    raise exception 'shipment_group_item_event_not_allowed';
  end if;

  select * into v_item
  from public.order_items
  where ord_no = v_ord_no and item_no = v_item_no
  for update;
  if not found then raise exception 'shipment_group_item_not_found'; end if;

  update public.order_items
  set o_shop_memo2 = v_memo2
  where ord_no = v_ord_no and item_no = v_item_no
  returning * into v_item;

  if nullif(btrim(coalesce(p_event_type, '')), '') is not null then
    insert into public.workflow_item_events (
      receipt_date,
      order_group_no,
      invoice_no,
      sellpia_item_no,
      sellpia_product_code,
      own_code,
      event_type,
      quantity,
      memo,
      drawer_memo,
      actor,
      source,
      payload
    )
    select
      coalesce(v_item.receipt_date, o.receipt_date),
      v_ord_no,
      coalesce(o.inv_no, ''),
      v_item_no,
      coalesce(v_item.p_code, ''),
      coalesce(v_item.prod_code, ''),
      p_event_type,
      p_quantity,
      nullif(v_memo2, ''),
      nullif(coalesce(p_drawer_memo, ''), ''),
      nullif(btrim(coalesce(p_updated_by, '')), ''),
      'f_v1_shipment_group',
      jsonb_build_object(
        'group_id', p_group_id,
        'productName', coalesce(v_item.p_name, ''),
        'optionName', coalesce(v_item.p_option, '')
      )
    from public.orders o
    where o.ord_no = v_ord_no
    returning * into v_event;

    if v_event.id is null then raise exception 'shipment_group_item_order_not_found'; end if;
  end if;

  if coalesce(p_auto_hold, false) and length(btrim(v_memo2)) > 0 then
    with changed_orders as (
      update public.orders o
      set system_shipping_hold_status = 'ON',
          system_shipping_hold_source = 'shipment_memo_auto_hold',
          system_shipping_hold_updated_at = now()
      where o.system_shipping_hold_status is distinct from 'ON'
        and exists (
          select 1
          from public.shipment_group_members m
          where m.group_id = p_group_id
            and m.active
            and m.ord_no = o.ord_no
        )
      returning o.*
    ), inserted_events as (
      insert into public.workflow_invoice_events (
        receipt_date,
        order_group_no,
        invoice_no,
        event_type,
        memo,
        actor,
        source,
        payload
      )
      select
        changed.receipt_date,
        changed.ord_no,
        coalesce(changed.inv_no, ''),
        'hold_created',
        'shipping hold auto on by shipment item memo save',
        nullif(btrim(coalesce(p_updated_by, '')), ''),
        'f_v1_shipment_group',
        jsonb_build_object('group_id', p_group_id, 'reason', 'item_memo2')
      from changed_orders changed
      returning order_group_no
    )
    select coalesce(array_agg(order_group_no order by order_group_no), array[]::text[])
      into v_held_ord_nos
    from inserted_events;
  end if;

  return jsonb_build_object(
    'item', to_jsonb(v_item),
    'event', case when v_event.id is null then null else to_jsonb(v_event) end,
    'held_ord_nos', to_jsonb(v_held_ord_nos)
  );
end;
$$;

revoke all on function public.shipment_group_snapshot(uuid) from public;
revoke all on function public.create_shipment_group(text[], text, text) from public;
revoke all on function public.change_shipment_representative(uuid, text, integer, text) from public;
revoke all on function public.release_shipment_group(uuid, integer, text) from public;
revoke all on function public.save_shipment_group_drawer_memo(uuid, text, integer, boolean, text) from public;
revoke all on function public.save_shipment_group_item_memo2(uuid, text, text, text, text, numeric, text, integer, boolean, text) from public;

grant execute on function public.shipment_group_snapshot(uuid) to anon, authenticated;
grant execute on function public.create_shipment_group(text[], text, text) to anon, authenticated;
grant execute on function public.change_shipment_representative(uuid, text, integer, text) to anon, authenticated;
grant execute on function public.release_shipment_group(uuid, integer, text) to anon, authenticated;
grant execute on function public.save_shipment_group_drawer_memo(uuid, text, integer, boolean, text) to anon, authenticated;
grant execute on function public.save_shipment_group_item_memo2(uuid, text, text, text, text, numeric, text, integer, boolean, text) to anon, authenticated;
