-- Alimtalk export and operator-confirmed send history.
-- This is intentionally independent from Sellpia order/item re-scrapes.

create table if not exists public.alimtalk_send_batches (
  id bigint generated by default as identity primary key,
  status text not null default 'exported',
  target_count integer not null default 0,
  created_by text null,
  confirmed_by text null,
  confirmed_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint alimtalk_send_batches_status_check check (status in ('exported', 'sent', 'failed', 'cancelled')),
  constraint alimtalk_send_batches_target_count_check check (target_count >= 0)
);

create table if not exists public.alimtalk_send_items (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.alimtalk_send_batches(id) on delete restrict,
  ord_no text not null,
  inv_no text null,
  template_key text not null,
  basis_date date null,
  status text not null default 'exported',
  sent_at timestamptz null,
  target_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint alimtalk_send_items_status_check check (status in ('exported', 'sent', 'failed', 'cancelled')),
  constraint alimtalk_send_items_batch_order_template_key unique (batch_id, ord_no, template_key)
);

create index if not exists alimtalk_send_batches_status_created_at_idx
  on public.alimtalk_send_batches (status, created_at desc);
create index if not exists alimtalk_send_items_sent_order_template_idx
  on public.alimtalk_send_items (status, ord_no, template_key);
create index if not exists alimtalk_send_items_batch_idx
  on public.alimtalk_send_items (batch_id);

create or replace function public.set_alimtalk_send_batches_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists alimtalk_send_batches_set_updated_at on public.alimtalk_send_batches;
create trigger alimtalk_send_batches_set_updated_at
before update on public.alimtalk_send_batches
for each row execute function public.set_alimtalk_send_batches_updated_at();

alter table public.alimtalk_send_batches enable row level security;
alter table public.alimtalk_send_items enable row level security;

revoke all on table public.alimtalk_send_batches from anon, authenticated;
revoke all on table public.alimtalk_send_items from anon, authenticated;
grant select, insert, update on table public.alimtalk_send_batches to anon, authenticated;
grant select, insert, update on table public.alimtalk_send_items to anon, authenticated;
grant usage, select on sequence public.alimtalk_send_batches_id_seq to anon, authenticated;
grant usage, select on sequence public.alimtalk_send_items_id_seq to anon, authenticated;

drop policy if exists "alimtalk send batches read" on public.alimtalk_send_batches;
drop policy if exists "alimtalk send batches create" on public.alimtalk_send_batches;
drop policy if exists "alimtalk send batches confirm" on public.alimtalk_send_batches;
create policy "alimtalk send batches read" on public.alimtalk_send_batches
  for select to anon, authenticated using (true);
create policy "alimtalk send batches create" on public.alimtalk_send_batches
  for insert to anon, authenticated
  with check (status = 'exported' and target_count >= 0);
create policy "alimtalk send batches confirm" on public.alimtalk_send_batches
  for update to anon, authenticated
  using (status = 'exported')
  with check (status in ('sent', 'failed', 'cancelled'));

drop policy if exists "alimtalk send items read" on public.alimtalk_send_items;
drop policy if exists "alimtalk send items create" on public.alimtalk_send_items;
drop policy if exists "alimtalk send items confirm" on public.alimtalk_send_items;
create policy "alimtalk send items read" on public.alimtalk_send_items
  for select to anon, authenticated using (true);
create policy "alimtalk send items create" on public.alimtalk_send_items
  for insert to anon, authenticated
  with check (status = 'exported' and length(btrim(ord_no)) > 0 and length(btrim(template_key)) > 0);
create policy "alimtalk send items confirm" on public.alimtalk_send_items
  for update to anon, authenticated
  using (status = 'exported')
  with check (status in ('sent', 'failed', 'cancelled'));
