-- CS 1-A: product-line current-state cases.
-- Deliberately no FK to order_items/orders: the Sellpia scraper replaces
-- order_items during a re-scrape, and CS manual state must survive that cycle.

create table if not exists public.cs_cases (
  id bigint generated by default as identity primary key,
  ord_no text not null,
  item_no text not null,
  sellpia_order_item_no text null,
  inv_no text null,
  receipt_date date null,

  case_type text not null,
  status text not null,
  source text not null,

  basis_date date null,
  basis_date_source text not null default 'receipt_date',

  assigned_to text null,
  resolved_at timestamptz null,
  excluded_at timestamptz null,

  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint cs_cases_status_check check (status in ('pending', 'resolved', 'excluded')),
  constraint cs_cases_source_check check (source in ('auto', 'manual')),
  constraint cs_cases_basis_date_source_check check (
    basis_date_source in ('receipt_date', 'manual', 'shortage_detected', 'hold_detected')
  ),
  constraint cs_cases_ord_item_type_key unique (ord_no, item_no, case_type)
);

create index if not exists cs_cases_status_type_basis_date_idx
  on public.cs_cases (status, case_type, basis_date);
create index if not exists cs_cases_ord_item_idx
  on public.cs_cases (ord_no, item_no);
create index if not exists cs_cases_status_updated_at_idx
  on public.cs_cases (status, updated_at desc);

create or replace function public.set_cs_cases_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists cs_cases_set_updated_at on public.cs_cases;
create trigger cs_cases_set_updated_at
before update on public.cs_cases
for each row execute function public.set_cs_cases_updated_at();

alter table public.cs_cases enable row level security;

-- The current application has no Supabase Auth session; this mirrors the
-- operational access model of workflow events, but prevents anon clients from
-- changing the immutable product identity, source, created metadata, or receipt
-- snapshot after creation. Replace with role/ownership policies when Auth lands.
revoke all on table public.cs_cases from anon, authenticated;
grant select, insert on table public.cs_cases to anon, authenticated;
grant update (
  case_type,
  status,
  basis_date,
  basis_date_source,
  assigned_to,
  resolved_at,
  excluded_at,
  updated_by,
  updated_at
) on table public.cs_cases to anon, authenticated;
grant usage, select on sequence public.cs_cases_id_seq to anon, authenticated;

drop policy if exists "cs cases read" on public.cs_cases;
drop policy if exists "cs cases create manual" on public.cs_cases;
drop policy if exists "cs cases update mutable state" on public.cs_cases;

create policy "cs cases read"
on public.cs_cases for select to anon, authenticated
using (true);

create policy "cs cases create manual"
on public.cs_cases for insert to anon, authenticated
with check (
  source = 'manual'
  and status = 'pending'
  and length(btrim(ord_no)) > 0
  and length(btrim(item_no)) > 0
  and length(btrim(case_type)) > 0
);

create policy "cs cases update mutable state"
on public.cs_cases for update to anon, authenticated
using (true)
with check (
  status in ('pending', 'resolved', 'excluded')
  and basis_date_source in ('receipt_date', 'manual', 'shortage_detected', 'hold_detected')
  and length(btrim(case_type)) > 0
);
